export default [
  await import('./user/user.js'),
  await import('./repos/repos.js'),
  await import('./pulls/pulls.js'),
  await import('./commits/commits.js'),
  await import('./issues/issues.js'),
  await import('./issue-timeline/issue-timeline.js'),
  await import('./comments/issue-comments.js'),
  await import('./comments/discussion-comments.js'),
  await import('./stars/stars.js'),
  await import('./reactions/reactions-issue.js'),
  await import('./reactions/reactions-issue-comments.js'),
  await import('./reactions/reactions-discussion-comments.js'),
  await import('./reactions/reactions-pull.js'),
  await import('./reactions/reactions-batch.js'),
] as const
