export default [
  await import('./abc-commit/abc-commit.js'),
  await import('./bad-words/bad-words.js'),
  await import('./cafe-commit/cafe-commit.js'),
  await import('./chore-commit/chore-commit.js'),
  await import('./cosmetic-commit/cosmetic-commit.js'),
  await import('./covid-19/covid-19.js'),
  await import('./dead-commit/dead-commit.js'),
  await import('./delorean/delorean.js'),
  await import('./emoji-only-commit/emoji-only-commit.js'),
  await import('./epic-commit/epic-commit.js'),
  await import('./favorite-word/favorite-word.js'),
  await import('./fix-commit/fix-commit.js'),
  await import('./github-anniversary/github-anniversary.js'),
  await import('./mass-delete-commit/mass-delete-commit.js'),
  // TODO: await import('./most-reactions/most-reactions.js'),
  await import('./my-badges-contributor/my-badges-contributor.js'),
  await import('./old-issue/old-issue.js'),
  await import('./polite-coder/polite-coder.js'),
  await import('./pr-collaboration/pr-collaboration.js'),
  await import('./public-keys/public-keys.js'),
  await import('./revert-revert-commit/revert-revert-commit.js'),
  await import('./spooky-commit/spooky-commit.js'),
  await import('./star-gazer/star-gazer.js'),
  await import('./stars/stars.js'),
  await import('./the-ultimate-question/the-ultimate-question.js'),
  await import('./this-is-fine/this-is-fine.js'),
  await import('./time-of-commit/time-of-commit.js'),
  await import('./yeti/yeti.js'),
] as const // keep sorted
